export interface Project {
  id: string;
  name: string;
  repoName: string;
  title: string;
  category: 'Enterprise & Portals' | 'E-Commerce & UMKM' | 'Management & ERP' | 'Smart City & Public';
  tagline: string;
  description: string;
  problem: string;
  solution: string;
  techStack: string[];
  githubUrl: string;
  liveDemoUrl?: string;
  featured: boolean;
  metrics: {
    label: string;
    value: string;
  }[];
  highlights: string[];
  imageUrl: string;
}

export const DEVELOPER_PROFILE = {
  name: 'Pangeran Ryan Pahlevi',
  role: 'Software Engineer & Full-Stack Web Developer',
  education: 'S1 Teknik Informatika — Universitas Budi Luhur',
  bio: 'Mahasiswa Teknik Informatika Universitas Budi Luhur dengan keahlian Full Stack Web & Mobile Development, UI/UX Design, serta Cyber Security (Network & Application Security). Memiliki pengalaman memimpin proyek perangkat lunak, mengembangkan CMS berbasis Laravel & FilamentPHP, sistem informasi akademik dan portal instansi, hingga aplikasi pemantauan kebencanaan geospasial.',
  email: 'pangeranryan080504@gmail.com',
  whatsapp: '6288224602608',
  whatsappFormatted: '0882-2460-2608',
  github: 'https://github.com/raphlv',
  instagram: 'https://instagram.com/jspryourbae',
  location: 'Jakarta, Indonesia',
  availability: 'Terbuka untuk diskusi proyek baru & kolaborasi',
  stats: [
    { label: 'Proyek GitHub Nyata', value: '21+' },
    { label: 'Pendidikan Sarjana', value: 'Budi Luhur' },
    { label: 'Sertifikasi Profesi', value: 'BNSP TKJ' },
    { label: 'Prestasi Nasional', value: 'Finalis GEMASTIK' },
  ],
};

export const CERTIFICATIONS = [
  {
    title: 'Sertifikat Kompetensi BNSP — Teknik Komputer Jaringan',
    issuer: 'Badan Nasional Sertifikasi Profesi (BNSP)',
    date: '10 Juni 2022',
    desc: 'Kompetensi nasional pengelolaan jaringan komputer, konfigurasi router/switch, dan keamanan infrastruktur.',
  },
  {
    title: 'Peraih Nominasi Kelompok Terpilih GEMASTIK',
    issuer: 'Pusat Prestasi Nasional / Balai Pengembangan Talenta Indonesia',
    date: 'Oktober 2023',
    desc: 'Berhasil terpilih dan meraih nominasi kelompok terbaik dari 357 kelompok kompetisi teknologi nasional.',
  },
];

export const WORK_EXPERIENCES = [
  {
    role: 'Lead Full-Stack & AI Systems Developer',
    organization: 'DIGISMART AI Public Communication',
    period: 'Agustus 2026 – Sekarang',
    location: 'Jakarta, Indonesia',
    type: 'AI Systems & Multi-Platform',
    highlights: [
      'Merancang arsitektur sistem komando komunikasi publik digital berbasis Next.js 14, TypeScript, dan Tailwind CSS.',
      'Mengintegrasikan AI News Generator (5W+1H), NLP Sentiment Analysis Engine, dan Quick Response Crisis Holding Statement.',
      'Mengemas aplikasi mandiri multi-platform untuk Desktop Windows (.EXE via Electron) dan Mobile Android (.APK via Capacitor).',
    ],
  },
  {
    role: 'Laravel & FilamentPHP Developer',
    organization: 'AHSA-CMS Platform',
    period: 'Mei 2026 – Juni 2026',
    location: 'Tangerang, Indonesia',
    type: 'CMS & Multi-Tenant Engine',
    highlights: [
      'Merancang modul page builder dan arsitektur template engine dinamis pada CMS multi-tenant berbasis Laravel.',
      'Menulis unit & feature testing dengan PestPHP (77 test case, 100% lulus) untuk menjamin stabilitas core CMS.',
      'Mengelola alur version control Git dan branching GitHub standar industri.',
    ],
  },
  {
    role: 'Full Stack Developer',
    organization: 'Rainfall Monitor & Early Disaster System',
    period: 'Mei 2026 – Juli 2026',
    location: 'Jakarta, Indonesia',
    type: 'Smart City & Public Systems',
    highlights: [
      'Membangun aplikasi pengumpulan data curah hujan real-time pos hidrologi untuk deteksi dini banjir perkotaan.',
      'Mengintegrasikan visualisasi grafik interaktif fluktuasi curah hujan periodik dan notifikasi batas aman.',
      'Menyediakan modul ekspor data hidrologi ke format Excel/CSV.',
    ],
  },
  {
    role: 'Full Stack Developer',
    organization: 'JIT Resolve IT Helpdesk & Service',
    period: 'Mei 2026',
    location: 'Jakarta, Indonesia',
    type: 'Management & Helpdesk Systems',
    highlights: [
      'Membangun portal penjualan paket konsultasi IT dan pelacakan status perbaikan perangkat.',
      'Mengembangkan modul live message bantuan teknis antara klien dan teknisi serta dashboard tiket prioritas.',
      'Mengintegrasikan notifikasi email otomatis saat ada pembaruan status perbaikan.',
    ],
  },
  {
    role: 'Full Stack Developer',
    organization: 'Golf Indonesia Platform',
    period: 'April 2026',
    location: 'Tangerang, Indonesia',
    type: 'Management & Competition Systems',
    highlights: [
      'Merancang skema database relasional turnamen golf nasional (Player, EventScore, EventPar).',
      'Mengembangkan leaderboard dinamis real-time dan optimasi SQL query untuk pemrosesan ribuan skor turnamen.',
      'Membangun antarmuka admin untuk transaksi yardage book digital dan cetak.',
    ],
  },
  {
    role: 'FrontEnd Developer',
    organization: 'Pengembangan Aplikasi Zakat',
    period: 'Maret 2025 – Juni 2025',
    location: 'Tangerang, Indonesia',
    type: 'Mobile & Web FrontEnd',
    highlights: [
      'Pengembangan aplikasi web & mobile menggunakan React dan React Native.',
      'Desain antarmuka responsif, integrasi API, pengujian lintas browser, dan praktik keamanan front-end.',
    ],
  },
  {
    role: 'UI Designer',
    organization: 'PT. Radar Teknologi Komputer',
    period: 'Maret 2025 – Juni 2025',
    location: 'Tangerang, Indonesia',
    type: 'UI/UX Design',
    highlights: [
      'Merancang visual komponen (tombol, ikon, tipografi) dan layout responsif multi-device.',
      'Memastikan konsistensi panduan desain (design guideline) dan implementasi bersama tim front-end.',
    ],
  },
  {
    role: 'Project Manager',
    organization: 'Pengembangan Aplikasi Student BudiLuhur',
    period: 'Februari 2024 – April 2024',
    location: 'Jakarta, Indonesia',
    type: 'Project Management & Leadership',
    highlights: [
      'Memimpin dan mengawasi keseluruhan siklus pengembangan proyek aplikasi mahasiswa.',
      'Mengoordinasikan tim lintas divisi, mengelola jadwal kerja, alokasi sumber daya, dan mitigasi kendala teknis.',
    ],
  },
  {
    role: 'FrontEnd Developer',
    organization: 'Pengembangan Aplikasi Perpustakaan',
    period: 'Oktober 2023 – Februari 2024',
    location: 'Jakarta, Indonesia',
    type: 'Web & Mobile Apps',
    highlights: [
      'Membangun aplikasi web dan mobile perpustakaan dengan React & React Native.',
      'Integrasi REST API, pengelolaan state aplikasi, dan optimasi performa antarmuka.',
    ],
  },
  {
    role: 'Staff IT & Network Engineer',
    organization: 'PT. Jaya Konsultan',
    period: 'Juni 2021 – Agustus 2021',
    location: 'Jakarta, Indonesia',
    type: 'IT Infrastructure & Networking',
    highlights: [
      'Mengelola dan memelihara jaringan lokal (LAN) dan area luas (WAN).',
      'Instalasi dan konfigurasi perangkat router, switch, firewall, dan troubleshooting kendala teknis pengguna.',
    ],
  },
];

export const ALL_PROJECTS: Project[] = [
  {
    id: 'bi-portal-next',
    name: 'Bank Indonesia Portal Next.js',
    repoName: 'bi-portal-next',
    title: 'Portal Web Resmi Bank Indonesia — Modern Central Bank Web Platform',
    category: 'Enterprise & Portals',
    tagline: 'Modernisasi portal resmi Bank Sentral RI dengan live monetary indicators ticker, JISDOR currency calculator, dan newsroom interaktif',
    description: 'Pengembangan ulang portal resmi Bank Indonesia (bi.go.id) menggunakan Next.js 14 App Router, TypeScript, dan Tailwind CSS. Menghadirkan identitas resmi Biru BI (#003F87) dan Aksen Emas (#C5A059), indikator moneter BI-Rate (6.00%), Inflasi (2.12%), Cadangan Devisa (USD 150.2B), kalkulator konversi valas JISDOR, dan repositori publikasi/regulasi.',
    problem: 'Situs web institusi bank sentral membutuhkan performa akses cepat, penyajian data kurs dan suku bunga acuan realtime yang presisi, serta tata kelola informasi kebijakan moneter yang mudah dipahami oleh publik dan pelaku pasar.',
    solution: 'Membangun portal modern Next.js 14 dengan arsitektur modular, widget kurs JISDOR interaktif, visualisasi grafik Recharts, command palette pencarian cerdas (Ctrl+K), dan navigasi mega menu komprehensif.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Recharts', 'Lucide-React'],
    githubUrl: 'https://github.com/raphlv/bi-portal-next',
    liveDemoUrl: '/bank-indonesia',
    featured: true,
    metrics: [
      { label: 'Indikator Moneter', value: 'Realtime' },
      { label: 'Konversi Valas', value: '8 Mata Uang' },
      { label: 'Kategori Regulasi', value: 'PBI & PADG' },
      { label: 'Performa Rute', value: '100% SSG' },
    ],
    highlights: [
      'Widget realtime BI-Rate, Inflasi, Cadangan Devisa, dan Kurs JISDOR USD/IDR.',
      'Kalkulator konversi valuta asing interaktif dengan pilihan kurs Tengah, Beli, dan Jual.',
      'Repositori publikasi Laporan Perekonomian Indonesia (LPI) dan direktori regulasi PBI.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1590283603385-17ffb3a7f29f?auto=format&fit=crop&w=800&q=80',
  },
  {
    id: 'digismart-next',
    name: 'DIGISMART v2.0',
    repoName: 'digismart-next',
    title: 'DIGISMART — AI Public Communication Command Center & Simulator',
    category: 'Smart City & Public',
    tagline: 'Platform instrumen kehumasan digital berbasis AI dengan generator berita 5W+1H, analisis sentimen NLP, dan respons krisis multi-platform',
    description: 'Sistem komando komunikasi publik digital yang dirancang untuk memantau dinamika percakapan netizen, memproduksi warta resmi dengan kecerdasan buatan, menganalisis polaritas opini publik, dan merumuskan holding statement respons krisis reputasi.',
    problem: 'Humas instansi dan periset komunikasi membutuhkan platform terpadu untuk mendeteksi krisis reputasi secara cepat dalam Golden Hour (< 60 menit) dan mengotomatisasi produksi siaran pers serta rilis multi-channel.',
    solution: 'Membangun aplikasi multi-platform (Web Next.js 14, Desktop Windows .EXE via Electron, dan Mobile Android .APK via Capacitor) dengan 8 modul interaktif, visualisasi tren SVG real-time, dan engine NLP sentimen.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Electron', 'Capacitor', 'NLP Engine'],
    githubUrl: 'https://github.com/raphlv/digismart-next',
    liveDemoUrl: 'http://localhost:3006',
    featured: true,
    metrics: [
      { label: 'Modul Interaktif', value: '8 Modul' },
      { label: 'Dukungan Platform', value: 'Web / EXE / APK' },
      { label: 'Respons Krisis', value: '< 60 Menit' },
      { label: 'Formula Jurnalistik', value: '5W + 1H' },
    ],
    highlights: [
      'Dashboard Command Center dengan visualisasi grafik tren SVG harian dan donut chart sentimen publik.',
      'AI News Generator 5W+1H dan generator Holding Statement krisis humas darurat.',
      'Kompilasi multi-platform mandiri menjadi installer Windows .EXE dan mobile Android .APK/PWA.',
    ],
    imageUrl: '/projects/digismart.png',
  },
  {
    id: 'brin-portal-next',
    name: 'BRIN Portal Next.js',
    repoName: 'brin-portal-next',
    title: 'Portal Web Badan Riset dan Inovasi Nasional (BRIN)',
    category: 'Enterprise & Portals',
    tagline: 'Modernisasi portal riset nasional dengan 12 Organisasi Riset dan katalog laboratorium terbuka',
    description: 'Pengembangan ulang portal resmi BRIN menggunakan Next.js 14 App Router, TypeScript, dan Tailwind CSS. Mengintegrasikan informasi 12 Organisasi Riset, 85 Pusat Riset, katalog layanan instrumen lab ELSA, serta skema pendanaan RIIM.',
    problem: 'Informasi dan layanan riset dari puluhan institusi yang melebur membutuhkan satu pintu akses terpadu yang cepat, rapi, dan mudah dinavigasi oleh sivitas periset maupun publik.',
    solution: 'Menerapkan Next.js 14 dengan Server-Side Rendering dan Static Site Generation, pencarian multi-kategori instan, tata letak simetris, dan panel dashboard monitoring data riset.',
    techStack: ['Next.js 14', 'React 18', 'TypeScript', 'Tailwind CSS'],
    githubUrl: 'https://github.com/raphlv/brin-portal-next',
    liveDemoUrl: 'http://localhost:3008',
    featured: true,
    metrics: [
      { label: 'Organisasi Riset', value: '12 OR' },
      { label: 'Pusat Riset', value: '85 PR' },
      { label: 'Katalog Alat Lab', value: '380+' },
      { label: 'Performa Rute', value: '100% SSG' },
    ],
    highlights: [
      'Pencarian instan multi-kategori untuk alat lab ELSA, skema pendanaan, dan profil organisasi riset.',
      'Halaman detail dinamis untuk seluruh 12 Organisasi Riset beserta invensi unggulan.',
      'Panel CMS Admin untuk memantau data riset dan publikasi warta.',
    ],
    imageUrl: '/projects/brin-portal.jpg',
  },
  {
    id: 'budiluhur-portal-next',
    name: 'Budi Luhur Portal Next.js',
    repoName: 'budiluhur-portal-next',
    title: 'Portal Web Resmi Universitas Budi Luhur',
    category: 'Enterprise & Portals',
    tagline: 'Portal informasi akademik dan fakultas berbasis Next.js 14 & Prisma ORM',
    description: 'Portal kampus Universitas Budi Luhur yang memuat informasi akademik, penerimaan mahasiswa baru (PMB), kegiatan riset, dan integrasi basis data Prisma ORM.',
    problem: 'Kebutuhan antarmuka web modern yang cepat dan terstruktur untuk mempermudah calon mahasiswa dan sivitas akademika mengakses informasi kampus.',
    solution: 'Membangun aplikasi Next.js 14 dengan dynamic routing, pemodelan database relasional Prisma, dan desain responsif sesuai identitas visual kampus.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Prisma ORM', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/budiluhur-portal-next',
    liveDemoUrl: 'http://localhost:3001',
    featured: true,
    metrics: [
      { label: 'Fakultas', value: '5 Fakultas' },
      { label: 'Database ORM', value: 'Prisma' },
      { label: 'Waktu Akses', value: '< 1 Detik' },
    ],
    highlights: [
      'Navigasi akademik terstruktur dan modul informasi PMB.',
      'Skema basis data relasional yang bersih dan mudah dikembangkan.',
    ],
    imageUrl: '/projects/budiluhur-portal.jpg',
  },
  {
    id: 'budiluhur-tv-next',
    name: 'Budi Luhur TV Platform',
    repoName: 'budiluhur-tv-next',
    title: 'Platform Media Kreatif & Penyiaran Budi Luhur TV',
    category: 'Enterprise & Portals',
    tagline: 'Portal media siaran kampus, liputan live report, dan katalog program acara',
    description: 'Platform web penyiaran untuk Budi Luhur TV dengan katalog program video, fitur laporan langsung dari lapangan (live report), dan profil tim produksi kreatif.',
    problem: 'Media kampus membutuhkan portal video yang rapi untuk mempublikasikan karya liputan jurnalistik dan program kreatif mahasiswa secara berkala.',
    solution: 'Merancang pemutar video responsif, sistem kategori acara mingguan, dan integrasi artikel berita liputan lapangan.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/budiluhur-tv-next',
    liveDemoUrl: 'http://localhost:3000',
    featured: true,
    metrics: [
      { label: 'Program Acara', value: '10+ Kategori' },
      { label: 'Kategori Liputan', value: 'Live & On-Demand' },
    ],
    highlights: [
      'Modul Live Report untuk update laporan langsung kegiatan kampus.',
      'Direktori tim produksi dan kru kreatif media.',
    ],
    imageUrl: '/projects/budiluhur-tv.jpg',
  },
  {
    id: 'radiobudiluhur-next',
    name: 'Radio Budi Luhur 107.7 FM',
    repoName: 'radiobudiluhur-next',
    title: 'Web Streaming & Audio Hub Radio Budi Luhur 107.7 FM',
    category: 'Enterprise & Portals',
    tagline: 'Streaming audio langsung, tangga lagu Chart Top 20, dan podcast on-demand',
    description: 'Platform streaming audio digital untuk Radio Budi Luhur 107.7 FM yang memungkinkan pendengar menikmati siaran radio secara online, melihat chart lagu mingguan, dan mendengarkan podcast.',
    problem: 'Perlunya sarana siaran daring agar pendengar di luar jangkauan pemancar radio analog FM tetap dapat mengakses siaran secara langsung.',
    solution: 'Mengembangkan audio player streaming yang berjalan stabil saat berpindah halaman, modul tangga lagu interaktif, dan arsip episode podcast.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Web Audio API'],
    githubUrl: 'https://github.com/raphlv/radiobudiluhur-next',
    liveDemoUrl: 'http://localhost:3005',
    featured: true,
    metrics: [
      { label: 'Frekuensi Siaran', value: '107.7 FM' },
      { label: 'Chart Mingguan', value: 'Top 20 Lagu' },
    ],
    highlights: [
      'Continuous Audio Player yang tetap menyala saat menjelajahi halaman.',
      'Sistem Chart Top 20 dengan update lagu berkala.',
    ],
    imageUrl: '/projects/budiluhur-tv.jpg',
  },
  {
    id: 'rental',
    name: 'Sistem Manajemen Rental Armada',
    repoName: 'rental',
    title: 'Aplikasi Manajemen Persewaan Kendaraan & Inventaris',
    category: 'Management & ERP',
    tagline: 'Sistem pencatatan armada kendaraan, reservasi, tarif sewa, dan laporan keuangan',
    description: 'Aplikasi berbasis web untuk bisnis rental kendaraan guna mengelola ketersediaan unit armada, transaksi sewa, denda keterlambatan, dan pencetakan invoice.',
    problem: 'Pencatatan rental yang masih manual berisiko menyebabkan jadwal sewa ganda (double-booking) dan kesulitan memantau status pengembalian unit.',
    solution: 'Membangun aplikasi terpusat dengan kalender ketersediaan armada, kalkulasi total biaya dan durasi otomatis, serta laporan transaksi berkala.',
    techStack: ['Laravel 11', 'PHP', 'Blade', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/rental',
    featured: true,
    metrics: [
      { label: 'Otomasi Tarif', value: 'Kalkulasi Otomatis' },
      { label: 'Laporan', value: 'Export Data' },
    ],
    highlights: [
      'Manajemen status armada (Tersedia, Disewa, Dalam Perawatan).',
      'Pencatatan data penyewa dan kalkulasi denda keterlambatan otomatis.',
    ],
    imageUrl: '/projects/arsitektur-sistem.png',
  },
  {
    id: 'kusuma-craft',
    name: 'Kusuma Craft E-Commerce',
    repoName: 'kusuma-craft',
    title: 'Website E-Commerce Katalog Produk Kerajinan Tangan',
    category: 'E-Commerce & UMKM',
    tagline: 'Katalog online produk kerajinan tangan, souvenir, dan pemesanan praktis',
    description: 'Website toko online untuk UMKM kerajinan tangan lokal yang menampilkan etalase foto produk berkualitas, rincian bahan baku, keranjang belanja, dan pemesanan langsung via WhatsApp.',
    problem: 'UMKM kerajinan tangan membutuhkan etalase digital yang mudah diakses calon pembeli dan instansi yang ingin memesan souvenir dalam jumlah banyak.',
    solution: 'Membuat web katalog produk yang bersih dan responsif, memudahkan pembeli memilih varian kerajinan dan langsung menghubungi pengrajin.',
    techStack: ['PHP', 'Laravel', 'Tailwind CSS', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/kusuma-craft',
    featured: true,
    metrics: [
      { label: 'Kategori Produk', value: 'Kerajinan Tangan' },
      { label: 'Pemesanan', value: 'WhatsApp Langsung' },
    ],
    highlights: [
      'Galeri foto produk yang rapi dengan rincian ukuran dan bahan.',
      'Sistem pemilihan item dan formulir pemesanan cepat.',
    ],
    imageUrl: '/projects/kusuma-craft.jpg',
  },
  {
    id: 'khumairasnack',
    name: 'Khumaira Snack E-Commerce',
    repoName: 'khumairasnack',
    title: 'Platform Penjualan Produk Camilan UMKM Khumaira',
    category: 'E-Commerce & UMKM',
    tagline: 'Katalog aneka camilan nusantara dan pemesanan online',
    description: 'Sistem penjualan online aneka snack dan camilan dengan kategori rasa, rincian berat produk, dan kemudahan pemesanan.',
    problem: 'Pencatatan order camilan yang tercecer di aplikasi pesan singkat.',
    solution: 'Menghadirkan katalog web terstruktur dengan ringkasan pesanan otomatis.',
    techStack: ['PHP', 'Bootstrap', 'MySQL', 'JavaScript'],
    githubUrl: 'https://github.com/raphlv/khumairasnack',
    featured: false,
    metrics: [
      { label: 'Menu Produk', value: '25+ Varian' },
    ],
    highlights: [
      'Penyusunan menu berdasarkan rasa manis, asin, dan paket hampers.',
    ],
    imageUrl: '/projects/khumairasnack.png',
  },
  {
    id: 'golf-indonesia',
    name: 'Golf Indonesia Platform',
    repoName: 'golf-indonesia',
    title: 'Sistem Informasi & Direktori Komunitas Golf',
    category: 'Management & ERP',
    tagline: 'Informasi lapangan golf, reservasi tee time, dan jadwal turnamen',
    description: 'Aplikasi web seputar olahraga golf yang memuat direktori lapangan, jadwal pemesanan waktu main (tee time), dan pendaftaran kompetisi.',
    problem: 'Pemain golf membutuhkan direktori lapangan terpadu untuk mengecek fasilitas dan reservasi jadwal main.',
    solution: 'Membangun aplikasi direktori lapangan dengan detail lokasi dan jadwal kegiatan.',
    techStack: ['PHP', 'Laravel', 'Blade', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/golf-indonesia',
    featured: false,
    metrics: [
      { label: 'Cakupan', value: 'Direktori Nasional' },
    ],
    highlights: [
      'Daftar lapangan golf dengan informasi fasilitas lengkap.',
    ],
    imageUrl: '/projects/wireframe-ui.png',
  },
  {
    id: 'bencana',
    name: 'Sistem Informasi Tanggap Bencana',
    repoName: 'bencana',
    title: 'Sistem Pemantauan & Pelaporan Kebencanaan Berbasis Peta',
    category: 'Smart City & Public',
    tagline: 'Pelaporan cepat kejadian bencana alam dan pemetaan titik posko bantuan',
    description: 'Aplikasi informasi kebencanaan yang memfasilitasi pelaporan kejadian darurat dari warga/relawan secara cepat dengan koordinat peta dan kebutuhan bantuan.',
    problem: 'Keterlambatan penyaluran logistik bencana akibat data sebaran korban dan posko yang belum terpetakan dengan baik.',
    solution: 'Dashboard pemetaan koordinat lokasi bencana dan pencatatan kebutuhan darurat.',
    techStack: ['PHP', 'Leaflet JS', 'Bootstrap', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/bencana',
    featured: true,
    metrics: [
      { label: 'Pemetaan', value: 'Koordinat Geospasial' },
    ],
    highlights: [
      'Peta visual titik bencana dan lokasi posko pengungsian.',
    ],
    imageUrl: '/projects/bencana.png',
  },
  {
    id: 'jit-resolve',
    name: 'JIT Resolve IT Helpdesk',
    repoName: 'jit-resolve',
    title: 'Sistem Manajemen Tiket Masalah TI Just-In-Time',
    category: 'Management & ERP',
    tagline: 'Pelacakan kendala perangkat lunak dan perangkat keras kantor',
    description: 'Aplikasi manajemen tiket kendala IT perusahaan untuk mengalokasikan penugasan teknisi dan memantau status penyelesaian masalah.',
    problem: 'Laporan kendala operasional komputer karyawan yang tidak tercatat rapi sehingga penanganannya terhambat.',
    solution: 'Alur tiket bertingkat (Open, In-Progress, Resolved) dengan pencatatan waktu penanganan.',
    techStack: ['Laravel', 'PHP', 'Blade', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/jit-resolve',
    featured: false,
    metrics: [
      { label: 'Status Tiket', value: 'Pelacakan Status' },
    ],
    highlights: [
      'Formulir submit kendala teknis dan dashboard monitoring beban teknisi.',
    ],
    imageUrl: '/projects/arsitektur-sistem.png',
  },
  {
    id: 'igakerta',
    name: 'Sistem Layanan Publik Desa Iga Kerta',
    repoName: 'igakerta',
    title: 'Portal Administrasi & Pelayanan Warga Desa',
    category: 'Smart City & Public',
    tagline: 'Pelayanan permohonan surat administrasi desa secara online',
    description: 'Aplikasi tata kelola desa untuk mempermudah warga mengajukan surat keterangan domisili atau usaha tanpa antre di kantor desa.',
    problem: 'Warga harus datang berulang kali ke kantor desa hanya untuk mengurus surat pengantar sederhana.',
    solution: 'Digitalisasi pengajuan surat dengan verifikasi digital dan arsip kependudukan yang rapi.',
    techStack: ['Laravel', 'Blade', 'MySQL', 'Bootstrap'],
    githubUrl: 'https://github.com/raphlv/igakerta',
    featured: false,
    metrics: [
      { label: 'Format Layanan', value: 'Surat Online' },
    ],
    highlights: [
      'Modul formulir surat warga dan transparansi data umum desa.',
    ],
    imageUrl: '/projects/flowchart-sistem.png',
  },
  {
    id: 'atlas',
    name: 'Atlas Gaming Gear E-Commerce',
    repoName: 'atlas',
    title: 'Aplikasi Web Katalog Produk Gaming Gear & Aksesoris',
    category: 'E-Commerce & UMKM',
    tagline: 'Katalog aksesoris gaming mobile, earbuds low latency, dan trigger controller',
    description: 'Platform e-commerce produk gaming gear mobile (Ares V1/V2, Frosttune Earbuds, Trigger Controller) dengan etalase visual modern dan spesifikasi perangkat.',
    problem: 'Pemain game mobile membutuhkan platform spesifik untuk mencari perlengkapan gaming yang kompatibel dengan ponsel mereka.',
    solution: 'Toko online interaktif dengan galeri produk gaming berkualitas tinggi dan integrasi marketplace.',
    techStack: ['Laravel', 'PHP', 'Tailwind CSS', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/atlas',
    featured: true,
    metrics: [
      { label: 'Produk Gear', value: 'Ares Series' },
    ],
    highlights: [
      'Galeri render 3D produk gaming gear dan spesifikasi teknis.',
    ],
    imageUrl: '/projects/atlas.png',
  },
  {
    id: 'apl_BankSampah',
    name: 'Aplikasi Bank Sampah Digital',
    repoName: 'apl_BankSampah',
    title: 'Sistem Pencatatan Tabungan Sampah Warga',
    category: 'Smart City & Public',
    tagline: 'Buku tabungan digital untuk konversi sampah terpilah menjadi saldo',
    description: 'Aplikasi pencatatan setoran sampah anorganik warga dengan konversi saldo rupiah otomatis sesuai jenis dan berat timbangan.',
    problem: 'Pencatatan setoran bank sampah di buku tulis sering rusak atau keliru hitung.',
    solution: 'Aplikasi buku tabungan digital dengan riwayat timbangan dan saldo nasabah yang jelas.',
    techStack: ['PHP', 'MySQL', 'JavaScript'],
    githubUrl: 'https://github.com/raphlv/apl_BankSampah',
    featured: false,
    metrics: [
      { label: 'Kategori', value: 'Plastik, Kertas, Logam' },
    ],
    highlights: [
      'Perhitungan otomatis saldo tabungan berdasarkan harga per kilogram.',
    ],
    imageUrl: '/projects/bencana-detail.png',
  },
  {
    id: 'siswa',
    name: 'Sistem Informasi Manajemen Siswa',
    repoName: 'siswa',
    title: 'Aplikasi Administrasi Data Siswa, Nilai, & Presensi',
    category: 'Management & ERP',
    tagline: 'Pengelolaan buku induk siswa, rekap nilai harian, dan kehadiran',
    description: 'Sistem administrasi akademik sekolah untuk mendata profil siswa, input nilai mata pelajaran oleh guru, dan rekapitulasi presensi.',
    problem: 'Guru memerlukan sistem terpadu untuk merekap nilai harian dan ujian tanpa risiko file spreadsheet tertimpa.',
    solution: 'Aplikasi web terpusat untuk penginputan nilai dan rekap presensi kelas.',
    techStack: ['PHP', 'MySQL', 'Bootstrap'],
    githubUrl: 'https://github.com/raphlv/siswa',
    featured: false,
    metrics: [
      { label: 'Data', value: 'Siswa & Nilai' },
    ],
    highlights: [
      'Input nilai bertingkat dan kalkulasi nilai rata-rata mata pelajaran.',
    ],
    imageUrl: '/projects/wireframe-ui.png',
  },
  {
    id: 'jurnal',
    name: 'Platform Jurnal Ilmiah Akademik',
    repoName: 'jurnal',
    title: 'Sistem Manajemen Publikasi Karya Ilmiah & Review',
    category: 'Enterprise & Portals',
    tagline: 'Alur penerbitan artikel ilmiah, review naskah, dan pengarsipan',
    description: 'Sistem manajemen artikel jurnal yang memfasilitasi alur pengajuan naskah oleh penulis, proses review oleh reviewer, dan penerbitan edisi berkala.',
    problem: 'Pengiriman artikel jurnal melalui email menyulitkan pemantauan riwayat revisi dan status naskah.',
    solution: 'Platform alur penelaahan naskah bertahap dari submission hingga publikasi.',
    techStack: ['PHP', 'MySQL', 'Tailwind CSS'],
    githubUrl: 'https://github.com/raphlv/jurnal',
    featured: false,
    metrics: [
      { label: 'Format', value: 'Open Access' },
    ],
    highlights: [
      'Pelacakan status naskah bagi penulis dan form penilaian reviewer.',
    ],
    imageUrl: '/projects/flowchart-sistem.png',
  },
  {
    id: 'zanilove',
    name: 'Zanilove Fashion & Beauty',
    repoName: 'zanilove',
    title: 'E-Commerce Katalog Busana & Produk Perawatan',
    category: 'E-Commerce & UMKM',
    tagline: 'Katalog fashion wanita, panduan ukuran busana, dan kontak order',
    description: 'Website katalog produk fashion dan kecantikan dengan tampilan bersih, foto detail produk, dan tombol tanya stok ke admin toko.',
    problem: 'Pembeli membutuhkan informasi bahan dan panduan ukuran busana sebelum melakukan transaksi.',
    solution: 'Katalog produk modern dengan informasi spesifikasi pakaian yang jelas.',
    techStack: ['PHP', 'HTML5/CSS3', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/zanilove',
    featured: false,
    metrics: [
      { label: 'Kategori', value: 'Fashion & Skincare' },
    ],
    highlights: [
      'Filter kategori pakaian dan tombol order terhubung ke customer service.',
    ],
    imageUrl: '/projects/zanilove.png',
  },
  {
    id: 'apl_Catering',
    name: 'Aplikasi Catering Sehat Online',
    repoName: 'apl_Catering',
    title: 'Sistem Pemesanan Paket Menu Catering Harian',
    category: 'E-Commerce & UMKM',
    tagline: 'Pemesanan paket menu makanan sehat dengan jadwal pengantaran fleksibel',
    description: 'Aplikasi web pemesanan menu makanan catering harian dengan pilihan jadwal kirim dan variasi paket diet.',
    problem: 'Penyedia catering memerlukan sistem untuk mencatat pesanan paket mingguan pelanggan secara rapi.',
    solution: 'Formulir pemesanan paket meal plan dengan opsi hari dan variasi menu.',
    techStack: ['PHP', 'HTML5/CSS3', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/apl_Catering',
    featured: false,
    metrics: [
      { label: 'Layanan', value: 'Catering Harian' },
    ],
    highlights: [
      'Pilihan menu mingguan dan pemilihan porsi makanan yang praktis.',
    ],
    imageUrl: '/projects/khumairasnack-products.png',
  },
  {
    id: 'jule-publicspeaking',
    name: 'Jule Public Speaking & Communication',
    repoName: 'jule-publicspeaking',
    title: 'Landing Page Pelatihan Komunikasi & Public Speaking',
    category: 'Enterprise & Portals',
    tagline: 'Informasi silabus kelas komunikasi, jadwal workshop, dan registrasi',
    description: 'Landing page promosi kelas pelatihan public speaking dengan penjelasan modul materi, profil instruktur, dan form pendaftaran kelas.',
    problem: 'Penyelenggara kursus membutuhkan landing page yang jelas untuk menyampaikan materi workshop dan menarik peserta baru.',
    solution: 'Landing page rapi dengan rincian silabus kelas dan tombol pendaftaran.',
    techStack: ['PHP', 'Tailwind CSS', 'HTML5'],
    githubUrl: 'https://github.com/raphlv/jule-publicspeaking',
    featured: false,
    metrics: [
      { label: 'Kelas', value: 'Pelatihan Komunikasi' },
    ],
    highlights: [
      'Silabus materi pelatihan dan formulir registrasi peserta.',
    ],
    imageUrl: '/projects/jule-publicspeaking.jpeg',
  },
  {
    id: 'stream-overlay',
    name: 'Stream Overlay Studio Suite',
    repoName: 'stream-overlay',
    title: 'Widget & Overlay Siaran Langsung Berbasis Web',
    category: 'Smart City & Public',
    tagline: 'Komponen overlay grafis ringan untuk live streaming OBS dan media siaran',
    description: 'Kumpulan widget dan grafik tampilan siaran langsung (lower-third, frame kamera, running text) yang dapat disematkan sebagai browser source di software penyiaran seperti OBS Studio.',
    problem: 'Kebutuhan grafik siaran yang ringan dan mudah dikustomisasi tanpa memberatkan komputer penyiaran.',
    solution: 'Overlay berbasis web standar HTML5/CSS3 yang berjalan mulus dan responsif.',
    techStack: ['JavaScript', 'HTML5 Canvas', 'CSS Animations'],
    githubUrl: 'https://github.com/raphlv/stream-overlay',
    featured: false,
    metrics: [
      { label: 'Kompatibilitas', value: 'OBS Studio / vMix' },
    ],
    highlights: [
      'Animasi lower-third dan penghitung waktu siaran yang ringan.',
    ],
    imageUrl: '/projects/stream-overlay.png',
  },
  {
    id: 'budiluhur-tv',
    name: 'Budi Luhur TV Core Laravel Engine',
    repoName: 'budiluhur-tv',
    title: 'Portal Media Siaran Kampus Berbasis Laravel 11',
    category: 'Enterprise & Portals',
    tagline: 'Sistem manajemen konten penyiaran dan autentikasi redaksi',
    description: 'Implementasi backend Laravel untuk Budi Luhur TV yang mengelola autentikasi redaksi, jadwal tayang, dan pengarsipan liputan.',
    problem: 'Perlunya panel pengelolaan konten yang aman bagi tim redaksi dan editor media kampus.',
    solution: 'Sistem otentikasi role-based access control di Laravel untuk pengelolaan liputan dan video.',
    techStack: ['Laravel 11', 'PHP', 'Blade', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/budiluhur-tv',
    featured: false,
    metrics: [
      { label: 'Backend', value: 'Laravel 11 MVC' },
    ],
    highlights: [
      'Dashboard manajemen jadwal siaran dan publikasi video.',
    ],
    imageUrl: '/projects/budiluhur-tv.jpg',
  },
];

export const SKILL_CATEGORIES = [
  {
    title: 'Full Stack & Web/Mobile Development',
    skills: [
      { name: 'Next.js 14 & React 18', level: 'Mahir', desc: 'App Router, Server Components, SSR/SSG' },
      { name: 'React Native & Mobile', level: 'Mahir', desc: 'Cross-platform mobile apps, status management' },
      { name: 'Laravel 11 & FilamentPHP', level: 'Mahir', desc: 'MVC architecture, Page Builder, PestPHP' },
      { name: 'TypeScript & JavaScript', level: 'Mahir', desc: 'Type-safe interfaces, ES6+, API integration' },
      { name: 'Tailwind CSS & UI/UX Design', level: 'Mahir', desc: 'Design systems, responsive interfaces, Figma' },
    ],
  },
  {
    title: 'Cyber Security & Network Infrastructure',
    skills: [
      { name: 'Network Security (LAN/WAN)', level: 'Bersertifikat BNSP', desc: 'Router, Switch, Firewall configuration' },
      { name: 'Application Security & PenTesting', level: 'Mahir', desc: 'Input validation, OWASP, penetration testing' },
      { name: 'Cryptography & Digital Forensics', level: 'Menengah', desc: 'Data protection, secure hashing, forensic analysis' },
      { name: 'Relational Database (MySQL/Prisma)', level: 'Mahir', desc: 'Relational schema, query optimization, indexing' },
    ],
  },
  {
    title: 'Project Management, Tools & Soft Skills',
    skills: [
      { name: 'Project Management & Leadership', level: 'Berpengalaman', desc: 'Perencanaan jadwal, koordinasi tim, resource management' },
      { name: 'Git & GitHub Workflow', level: 'Mahir', desc: 'Branching, PR, version control, CI/CD' },
      { name: 'Problem Solving & Critical Thinking', level: 'Tinggi', desc: 'Troubleshooting sistematis, pemecahan masalah' },
      { name: 'Public Speaking & Communication', level: 'Baik', desc: 'Presentasi teknis, komunikasi klien & tim' },
    ],
  },
];
