export interface Project {
  id: string;
  name: string;
  repoName: string;
  title: string;
  category: 'Enterprise & Portals' | 'E-Commerce & UMKM' | 'Management & ERP' | 'Smart City & Public';
  tagline: string;
  description: string;
  problem: string;
  solution: string;
  techStack: string[];
  githubUrl: string;
  liveDemoUrl?: string;
  featured: boolean;
  metrics: {
    label: string;
    value: string;
  }[];
  highlights: string[];
  imageUrl: string;
}

export const DEVELOPER_PROFILE = {
  name: 'Pangeran Ryan Pahlevi',
  role: 'Software Engineer & Full-Stack Web Developer',
  tagline: 'Mengembangkan aplikasi web modern, cepat, dan terstruktur rapi untuk instansi dan bisnis.',
  bio: 'Pengembang web berbasis di Jakarta dengan fokus utama pada ekosistem Next.js, React, TypeScript, dan Laravel. Memiliki rekam jejak mengembangkan berbagai aplikasi nyata mulai dari portal riset skala nasional, sistem informasi kampus, platform media siaran, e-commerce, hingga sistem manajemen operasional.',
  email: 'pangeranryan080504@gmail.com',
  whatsapp: '6288224602608',
  whatsappFormatted: '0882-2460-2608',
  github: 'https://github.com/raphlv',
  location: 'Jakarta, Indonesia',
  availability: 'Terbuka untuk diskusi proyek baru & kerjasama',
  stats: [
    { label: 'Proyek Repositori GitHub', value: '20+' },
    { label: 'Teknologi & Framework', value: '10+' },
    { label: 'Waktu Muat Rata-Rata', value: '< 1 Detik' },
    { label: 'Pendekatan Kode', value: 'Clean & Modular' },
  ],
};

export const ALL_PROJECTS: Project[] = [
  {
    id: 'brin-portal-next',
    name: 'BRIN Portal Next.js',
    repoName: 'brin-portal-next',
    title: 'Portal Web Badan Riset dan Inovasi Nasional (BRIN)',
    category: 'Enterprise & Portals',
    tagline: 'Modernisasi portal riset nasional dengan 12 Organisasi Riset dan katalog laboratorium terbuka',
    description: 'Pengembangan ulang portal resmi BRIN menggunakan Next.js 14 App Router, TypeScript, dan Tailwind CSS. Mengintegrasikan informasi 12 Organisasi Riset, 85 Pusat Riset, katalog layanan instrumen lab ELSA, serta skema pendanaan RIIM.',
    problem: 'Informasi dan layanan riset dari puluhan institusi yang melebur membutuhkan satu pintu akses terpadu yang cepat, rapi, dan mudah dinavigasi oleh sivitas periset maupun publik.',
    solution: 'Menerapkan Next.js 14 dengan Server-Side Rendering dan Static Site Generation, pencarian multi-kategori instan, tata letak simetris, dan panel dashboard monitoring data riset.',
    techStack: ['Next.js 14', 'React 18', 'TypeScript', 'Tailwind CSS'],
    githubUrl: 'https://github.com/raphlv/brin-portal-next',
    liveDemoUrl: 'http://localhost:3008',
    featured: true,
    metrics: [
      { label: 'Organisasi Riset', value: '12 OR' },
      { label: 'Pusat Riset', value: '85 PR' },
      { label: 'Katalog Alat Lab', value: '380+' },
      { label: 'Performa Rute', value: '100% SSG' },
    ],
    highlights: [
      'Pencarian instan multi-kategori untuk alat lab ELSA, skema pendanaan, dan profil organisasi riset.',
      'Halaman detail dinamis untuk seluruh 12 Organisasi Riset beserta invensi unggulan.',
      'Panel CMS Admin untuk memantau data riset dan publikasi warta.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'budiluhur-portal-next',
    name: 'Budi Luhur Portal Next.js',
    repoName: 'budiluhur-portal-next',
    title: 'Portal Web Resmi Universitas Budi Luhur',
    category: 'Enterprise & Portals',
    tagline: 'Portal informasi akademik dan fakultas berbasis Next.js 14 & Prisma ORM',
    description: 'Portal kampus Universitas Budi Luhur yang memuat informasi akademik, penerimaan mahasiswa baru (PMB), kegiatan riset, dan integrasi basis data Prisma ORM.',
    problem: 'Kebutuhan antarmuka web modern yang cepat dan terstruktur untuk mempermudah calon mahasiswa dan sivitas akademika mengakses informasi kampus.',
    solution: 'Membangun aplikasi Next.js 14 dengan dynamic routing, pemodelan database relasional Prisma, dan desain responsif sesuai identitas visual kampus.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Prisma ORM', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/budiluhur-portal-next',
    liveDemoUrl: 'http://localhost:3001',
    featured: true,
    metrics: [
      { label: 'Fakultas', value: '5 Fakultas' },
      { label: 'Database ORM', value: 'Prisma' },
      { label: 'Waktu Akses', value: '< 1 Detik' },
    ],
    highlights: [
      'Navigasi akademik terstruktur dan modul informasi PMB.',
      'Skema basis data relasional yang bersih dan mudah dikembangkan.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'budiluhur-tv-next',
    name: 'Budi Luhur TV Platform',
    repoName: 'budiluhur-tv-next',
    title: 'Platform Media Kreatif & Penyiaran Budi Luhur TV',
    category: 'Enterprise & Portals',
    tagline: 'Portal media siaran kampus, liputan live report, dan katalog program acara',
    description: 'Platform web penyiaran untuk Budi Luhur TV dengan katalog program video, fitur laporan langsung dari lapangan (live report), dan profil tim produksi kreatif.',
    problem: 'Media kampus membutuhkan portal video yang rapi untuk mempublikasikan karya liputan jurnalistik dan program kreatif mahasiswa secara berkala.',
    solution: 'Merancang pemutar video responsif, sistem kategori acara mingguan, dan integrasi artikel berita liputan lapangan.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/budiluhur-tv-next',
    liveDemoUrl: 'http://localhost:3000',
    featured: true,
    metrics: [
      { label: 'Program Acara', value: '10+ Kategori' },
      { label: 'Kategori Liputan', value: 'Live & On-Demand' },
    ],
    highlights: [
      'Modul Live Report untuk update laporan langsung kegiatan kampus.',
      'Direktori tim produksi dan kru kreatif media.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'radiobudiluhur-next',
    name: 'Radio Budi Luhur 107.7 FM',
    repoName: 'radiobudiluhur-next',
    title: 'Web Streaming & Audio Hub Radio Budi Luhur 107.7 FM',
    category: 'Enterprise & Portals',
    tagline: 'Streaming audio langsung, tangga lagu Chart Top 20, dan podcast on-demand',
    description: 'Platform streaming audio digital untuk Radio Budi Luhur 107.7 FM yang memungkinkan pendengar menikmati siaran radio secara online, melihat chart lagu mingguan, dan mendengarkan podcast.',
    problem: 'Perlunya sarana siaran daring agar pendengar di luar jangkauan pemancar radio analog FM tetap dapat mengakses siaran secara langsung.',
    solution: 'Mengembangkan audio player streaming yang berjalan stabil saat berpindah halaman, modul tangga lagu interaktif, dan arsip episode podcast.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Web Audio API'],
    githubUrl: 'https://github.com/raphlv/radiobudiluhur-next',
    liveDemoUrl: 'http://localhost:3005',
    featured: true,
    metrics: [
      { label: 'Frekuensi Siaran', value: '107.7 FM' },
      { label: 'Chart Mingguan', value: 'Top 20 Lagu' },
    ],
    highlights: [
      'Continuous Audio Player yang tetap menyala saat menjelajahi halaman.',
      'Sistem Chart Top 20 dengan update lagu berkala.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'rental',
    name: 'Sistem Manajemen Rental Armada',
    repoName: 'rental',
    title: 'Aplikasi Manajemen Persewaan Kendaraan & Inventaris',
    category: 'Management & ERP',
    tagline: 'Sistem pencatatan armada kendaraan, reservasi, tarif sewa, dan laporan keuangan',
    description: 'Aplikasi berbasis web untuk bisnis rental kendaraan guna mengelola ketersediaan unit armada, transaksi sewa, denda keterlambatan, dan pencetakan invoice.',
    problem: 'Pencatatan rental yang masih manual berisiko menyebabkan jadwal sewa ganda (double-booking) dan kesulitan memantau status pengembalian unit.',
    solution: 'Membangun aplikasi terpusat dengan kalender ketersediaan armada, kalkulasi total biaya dan durasi otomatis, serta laporan transaksi berkala.',
    techStack: ['Laravel 11', 'PHP', 'Blade', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/rental',
    featured: true,
    metrics: [
      { label: 'Otomasi Tarif', value: 'Kalkulasi Otomatis' },
      { label: 'Laporan', value: 'Export Data' },
    ],
    highlights: [
      'Manajemen status armada (Tersedia, Disewa, Dalam Perawatan).',
      'Pencatatan data penyewa dan kalkulasi denda keterlambatan otomatis.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'kusuma-craft',
    name: 'Kusuma Craft E-Commerce',
    repoName: 'kusuma-craft',
    title: 'Website E-Commerce Katalog Produk Kerajinan Tangan',
    category: 'E-Commerce & UMKM',
    tagline: 'Katalog online produk kerajinan tangan, souvenir, dan pemesanan praktis',
    description: 'Website toko online untuk UMKM kerajinan tangan lokal yang menampilkan etalase foto produk berkualitas, rincian bahan baku, keranjang belanja, dan pemesanan langsung via WhatsApp.',
    problem: 'UMKM kerajinan tangan membutuhkan etalase digital yang mudah diakses calon pembeli dan instansi yang ingin memesan souvenir dalam jumlah banyak.',
    solution: 'Membuat web katalog produk yang bersih dan responsif, memudahkan pembeli memilih varian kerajinan dan langsung menghubungi pengrajin.',
    techStack: ['PHP', 'Laravel', 'Tailwind CSS', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/kusuma-craft',
    featured: true,
    metrics: [
      { label: 'Kategori Produk', value: 'Kerajinan Tangan' },
      { label: 'Pemesanan', value: 'WhatsApp Langsung' },
    ],
    highlights: [
      'Galeri foto produk yang rapi dengan rincian ukuran dan bahan.',
      'Sistem pemilihan item dan formulir pemesanan cepat.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'khumairasnack',
    name: 'Khumaira Snack E-Commerce',
    repoName: 'khumairasnack',
    title: 'Platform Penjualan Produk Camilan UMKM Khumaira',
    category: 'E-Commerce & UMKM',
    tagline: 'Katalog aneka camilan nusantara dan pemesanan online',
    description: 'Sistem penjualan online aneka snack dan camilan dengan kategori rasa, rincian berat produk, dan kemudahan pemesanan.',
    problem: 'Pencatatan order camilan yang tercecer di aplikasi pesan singkat.',
    solution: 'Menghadirkan katalog web terstruktur dengan ringkasan pesanan otomatis.',
    techStack: ['PHP', 'Bootstrap', 'MySQL', 'JavaScript'],
    githubUrl: 'https://github.com/raphlv/khumairasnack',
    featured: false,
    metrics: [
      { label: 'Menu Produk', value: '25+ Varian' },
    ],
    highlights: [
      'Penyusunan menu berdasarkan rasa manis, asin, dan paket hampers.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'golf-indonesia',
    name: 'Golf Indonesia Platform',
    repoName: 'golf-indonesia',
    title: 'Sistem Informasi & Direktori Komunitas Golf',
    category: 'Management & ERP',
    tagline: 'Informasi lapangan golf, reservasi tee time, dan jadwal turnamen',
    description: 'Aplikasi web seputar olahraga golf yang memuat direktori lapangan, jadwal pemesanan waktu main (tee time), dan pendaftaran kompetisi.',
    problem: 'Pemain golf membutuhkan direktori lapangan terpadu untuk mengecek fasilitas dan reservasi jadwal main.',
    solution: 'Membangun aplikasi direktori lapangan dengan detail lokasi dan jadwal kegiatan.',
    techStack: ['PHP', 'Laravel', 'Blade', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/golf-indonesia',
    featured: false,
    metrics: [
      { label: 'Cakupan', value: 'Direktori Nasional' },
    ],
    highlights: [
      'Daftar lapangan golf dengan informasi fasilitas lengkap.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'bencana',
    name: 'Sistem Informasi Tanggap Bencana',
    repoName: 'bencana',
    title: 'Sistem Pemantauan & Pelaporan Kebencanaan Berbasis Peta',
    category: 'Smart City & Public',
    tagline: 'Pelaporan cepat kejadian bencana alam dan pemetaan titik posko bantuan',
    description: 'Aplikasi informasi kebencanaan yang memfasilitasi pelaporan kejadian darurat dari warga/relawan secara cepat dengan koordinat peta dan kebutuhan bantuan.',
    problem: 'Keterlambatan penyaluran logistik bencana akibat data sebaran korban dan posko yang belum terpetakan dengan baik.',
    solution: 'Dashboard pemetaan koordinat lokasi bencana dan pencatatan kebutuhan darurat.',
    techStack: ['PHP', 'Leaflet JS', 'Bootstrap', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/bencana',
    featured: true,
    metrics: [
      { label: 'Pemetaan', value: 'Koordinat Geospasial' },
    ],
    highlights: [
      'Peta visual titik bencana dan lokasi posko pengungsian.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'jit-resolve',
    name: 'JIT Resolve IT Helpdesk',
    repoName: 'jit-resolve',
    title: 'Sistem Manajemen Tiket Masalah TI Just-In-Time',
    category: 'Management & ERP',
    tagline: 'Pelacakan kendala perangkat lunak dan perangkat keras kantor',
    description: 'Aplikasi manajemen tiket kendala IT perusahaan untuk mengalokasikan penugasan teknisi dan memantau status penyelesaian masalah.',
    problem: 'Laporan kendala operasional komputer karyawan yang tidak tercatat rapi sehingga penanganannya terhambat.',
    solution: 'Alur tiket bertingkat (Open, In-Progress, Resolved) dengan pencatatan waktu penanganan.',
    techStack: ['Laravel', 'PHP', 'Blade', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/jit-resolve',
    featured: false,
    metrics: [
      { label: 'Status Tiket', value: 'Pelacakan Status' },
    ],
    highlights: [
      'Formulir submit kendala teknis dan dashboard monitoring beban teknisi.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'igakerta',
    name: 'Sistem Layanan Publik Desa Iga Kerta',
    repoName: 'igakerta',
    title: 'Portal Administrasi & Pelayanan Warga Desa',
    category: 'Smart City & Public',
    tagline: 'Pelayanan permohonan surat administrasi desa secara online',
    description: 'Aplikasi tata kelola desa untuk mempermudah warga mengajukan surat keterangan domisili atau usaha tanpa antre di kantor desa.',
    problem: 'Warga harus datang berulang kali ke kantor desa hanya untuk mengurus surat pengantar sederhana.',
    solution: 'Digitalisasi pengajuan surat dengan verifikasi digital dan arsip kependudukan yang rapi.',
    techStack: ['Laravel', 'Blade', 'MySQL', 'Bootstrap'],
    githubUrl: 'https://github.com/raphlv/igakerta',
    featured: false,
    metrics: [
      { label: 'Format Layanan', value: 'Surat Online' },
    ],
    highlights: [
      'Modul formulir surat warga dan transparansi data umum desa.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'atlas',
    name: 'Atlas GIS Pemetaan Spasial',
    repoName: 'atlas',
    title: 'Aplikasi Web Pemetaan Interaktif & Data Spasial',
    category: 'Smart City & Public',
    tagline: 'Visualisasi layer batas wilayah dan sebaran fasilitas publik',
    description: 'Platform visualisasi data geografis yang menampilkan batas wilayah dan titik fasilitas publik berbasis GeoJSON.',
    problem: 'Visualisasi data wilayah sulit dipahami jika hanya berupa tabel angka tanpa representasi visual pada peta.',
    solution: 'Membuat web GIS interaktif yang dapat memfilter layer infrastruktur dan zonasi.',
    techStack: ['PHP', 'JavaScript', 'Leaflet', 'GeoJSON', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/atlas',
    featured: false,
    metrics: [
      { label: 'Format Peta', value: 'GeoJSON Layer' },
    ],
    highlights: [
      'Peta interaktif dengan informasi detail pada setiap titik wilayah.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'apl_BankSampah',
    name: 'Aplikasi Bank Sampah Digital',
    repoName: 'apl_BankSampah',
    title: 'Sistem Pencatatan Tabungan Sampah Warga',
    category: 'Smart City & Public',
    tagline: 'Buku tabungan digital untuk konversi sampah terpilah menjadi saldo',
    description: 'Aplikasi pencatatan setoran sampah anorganik warga dengan konversi saldo rupiah otomatis sesuai jenis dan berat timbangan.',
    problem: 'Pencatatan setoran bank sampah di buku tulis sering rusak atau keliru hitung.',
    solution: 'Aplikasi buku tabungan digital dengan riwayat timbangan dan saldo nasabah yang jelas.',
    techStack: ['PHP', 'MySQL', 'JavaScript'],
    githubUrl: 'https://github.com/raphlv/apl_BankSampah',
    featured: false,
    metrics: [
      { label: 'Kategori', value: 'Plastik, Kertas, Logam' },
    ],
    highlights: [
      'Perhitungan otomatis saldo tabungan berdasarkan harga per kilogram.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'siswa',
    name: 'Sistem Informasi Manajemen Siswa',
    repoName: 'siswa',
    title: 'Aplikasi Administrasi Data Siswa, Nilai, & Presensi',
    category: 'Management & ERP',
    tagline: 'Pengelolaan buku induk siswa, rekap nilai harian, dan kehadiran',
    description: 'Sistem administrasi akademik sekolah untuk mendata profil siswa, input nilai mata pelajaran oleh guru, dan rekapitulasi presensi.',
    problem: 'Guru memerlukan sistem terpadu untuk merekap nilai harian dan ujian tanpa risiko file spreadsheet tertimpa.',
    solution: 'Aplikasi web terpusat untuk penginputan nilai dan rekap presensi kelas.',
    techStack: ['PHP', 'MySQL', 'Bootstrap'],
    githubUrl: 'https://github.com/raphlv/siswa',
    featured: false,
    metrics: [
      { label: 'Data', value: 'Siswa & Nilai' },
    ],
    highlights: [
      'Input nilai bertingkat dan kalkulasi nilai rata-rata mata pelajaran.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'jurnal',
    name: 'Platform Jurnal Ilmiah Akademik',
    repoName: 'jurnal',
    title: 'Sistem Manajemen Publikasi Karya Ilmiah & Review',
    category: 'Enterprise & Portals',
    tagline: 'Alur penerbitan artikel ilmiah, review naskah, dan pengarsipan',
    description: 'Sistem manajemen artikel jurnal yang memfasilitasi alur pengajuan naskah oleh penulis, proses review oleh reviewer, dan penerbitan edisi berkala.',
    problem: 'Pengiriman artikel jurnal melalui email menyulitkan pemantauan riwayat revisi dan status naskah.',
    solution: 'Platform alur penelaahan naskah bertahap dari submission hingga publikasi.',
    techStack: ['PHP', 'MySQL', 'Tailwind CSS'],
    githubUrl: 'https://github.com/raphlv/jurnal',
    featured: false,
    metrics: [
      { label: 'Format', value: 'Open Access' },
    ],
    highlights: [
      'Pelacakan status naskah bagi penulis dan form penilaian reviewer.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'zanilove',
    name: 'Zanilove Fashion & Beauty',
    repoName: 'zanilove',
    title: 'E-Commerce Katalog Busana & Produk Perawatan',
    category: 'E-Commerce & UMKM',
    tagline: 'Katalog fashion wanita, panduan ukuran busana, dan kontak order',
    description: 'Website katalog produk fashion dan kecantikan dengan tampilan bersih, foto detail produk, dan tombol tanya stok ke admin toko.',
    problem: 'Pembeli membutuhkan informasi bahan dan panduan ukuran busana sebelum melakukan transaksi.',
    solution: 'Katalog produk modern dengan informasi spesifikasi pakaian yang jelas.',
    techStack: ['PHP', 'HTML5/CSS3', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/zanilove',
    featured: false,
    metrics: [
      { label: 'Kategori', value: 'Fashion & Skincare' },
    ],
    highlights: [
      'Filter kategori pakaian dan tombol order terhubung ke customer service.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'apl_Catering',
    name: 'Aplikasi Catering Sehat Online',
    repoName: 'apl_Catering',
    title: 'Sistem Pemesanan Paket Menu Catering Harian',
    category: 'E-Commerce & UMKM',
    tagline: 'Pemesanan paket menu makanan sehat dengan jadwal pengantaran fleksibel',
    description: 'Aplikasi web pemesanan menu makanan catering harian dengan pilihan jadwal kirim dan variasi paket diet.',
    problem: 'Penyedia catering memerlukan sistem untuk mencatat pesanan paket mingguan pelanggan secara rapi.',
    solution: 'Formulir pemesanan paket meal plan dengan opsi hari dan variasi menu.',
    techStack: ['PHP', 'HTML5/CSS3', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/apl_Catering',
    featured: false,
    metrics: [
      { label: 'Layanan', value: 'Catering Harian' },
    ],
    highlights: [
      'Pilihan menu mingguan dan pemilihan porsi makanan yang praktis.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1555244162-803834f70033?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'jule-publicspeaking',
    name: 'Jule Public Speaking & Communication',
    repoName: 'jule-publicspeaking',
    title: 'Landing Page Pelatihan Komunikasi & Public Speaking',
    category: 'Enterprise & Portals',
    tagline: 'Informasi silabus kelas komunikasi, jadwal workshop, dan registrasi',
    description: 'Landing page promosi kelas pelatihan public speaking dengan penjelasan modul materi, profil instruktur, dan form pendaftaran kelas.',
    problem: 'Penyelenggara kursus membutuhkan landing page yang jelas untuk menyampaikan materi workshop dan menarik peserta baru.',
    solution: 'Landing page rapi dengan rincian silabus kelas dan tombol pendaftaran.',
    techStack: ['PHP', 'Tailwind CSS', 'HTML5'],
    githubUrl: 'https://github.com/raphlv/jule-publicspeaking',
    featured: false,
    metrics: [
      { label: 'Kelas', value: 'Pelatihan Komunikasi' },
    ],
    highlights: [
      'Silabus materi pelatihan dan formulir registrasi peserta.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'stream-overlay',
    name: 'Stream Overlay Studio Suite',
    repoName: 'stream-overlay',
    title: 'Widget & Overlay Siaran Langsung Berbasis Web',
    category: 'Smart City & Public',
    tagline: 'Komponen overlay grafis ringan untuk live streaming OBS dan media siaran',
    description: 'Kumpulan widget dan grafik tampilan siaran langsung (lower-third, frame kamera, running text) yang dapat disematkan sebagai browser source di software penyiaran seperti OBS Studio.',
    problem: 'Kebutuhan grafik siaran yang ringan dan mudah dikustomisasi tanpa memberatkan komputer penyiaran.',
    solution: 'Overlay berbasis web standar HTML5/CSS3 yang berjalan mulus dan responsif.',
    techStack: ['JavaScript', 'HTML5 Canvas', 'CSS Animations'],
    githubUrl: 'https://github.com/raphlv/stream-overlay',
    featured: false,
    metrics: [
      { label: 'Kompatibilitas', value: 'OBS Studio / vMix' },
    ],
    highlights: [
      'Animasi lower-third dan penghitung waktu siaran yang ringan.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'budiluhur-tv',
    name: 'Budi Luhur TV Core Laravel Engine',
    repoName: 'budiluhur-tv',
    title: 'Portal Media Siaran Kampus Berbasis Laravel 11',
    category: 'Enterprise & Portals',
    tagline: 'Sistem manajemen konten penyiaran dan autentikasi redaksi',
    description: 'Implementasi backend Laravel untuk Budi Luhur TV yang mengelola autentikasi redaksi, jadwal tayang, dan pengarsipan liputan.',
    problem: 'Perlunya panel pengelolaan konten yang aman bagi tim redaksi dan editor media kampus.',
    solution: 'Sistem otentikasi role-based access control di Laravel untuk pengelolaan liputan dan video.',
    techStack: ['Laravel 11', 'PHP', 'Blade', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/budiluhur-tv',
    featured: false,
    metrics: [
      { label: 'Backend', value: 'Laravel 11 MVC' },
    ],
    highlights: [
      'Dashboard manajemen jadwal siaran dan publikasi video.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1000&auto=format&fit=crop',
  },
];

export const SKILL_CATEGORIES = [
  {
    title: 'Frontend Development',
    skills: [
      { name: 'Next.js 14 (App Router)', level: 'Mahir', desc: 'Server Components, SSR, SSG' },
      { name: 'React 18 & Hooks', level: 'Mahir', desc: 'Custom hooks, state management' },
      { name: 'TypeScript', level: 'Mahir', desc: 'Strict typing, modular interfaces' },
      { name: 'Tailwind CSS', level: 'Mahir', desc: 'Custom design systems, responsive UI' },
    ],
  },
  {
    title: 'Backend & Database',
    skills: [
      { name: 'Laravel 11 & PHP', level: 'Mahir', desc: 'MVC architecture, RESTful API' },
      { name: 'Node.js & Express', level: 'Menengah', desc: 'API services, middleware' },
      { name: 'Prisma ORM', level: 'Mahir', desc: 'Type-safe relational database' },
      { name: 'MySQL & PostgreSQL', level: 'Mahir', desc: 'Relational schema, query optimization' },
    ],
  },
  {
    title: 'Tools & Workflow',
    skills: [
      { name: 'Git & GitHub Workflow', level: 'Mahir', desc: 'Version control, branch management' },
      { name: 'Vercel / Cloud Hosting', level: 'Mahir', desc: 'Automated CI/CD deployment' },
      { name: 'SEO & Web Performance', level: 'Mahir', desc: 'Core Web Vitals, metadata, caching' },
      { name: 'REST API & Webhooks', level: 'Mahir', desc: 'Third-party service integrations' },
    ],
  },
];
