export interface Project {
  id: string;
  name: string;
  repoName: string;
  title: string;
  category: 'Enterprise & Portals' | 'E-Commerce & UMKM' | 'Management & ERP' | 'Smart City & Public';
  tagline: string;
  description: string;
  problem: string;
  solution: string;
  techStack: string[];
  githubUrl: string;
  liveDemoUrl?: string;
  featured: boolean;
  metrics: {
    label: string;
    value: string;
  }[];
  highlights: string[];
  imageUrl: string;
}

export const DEVELOPER_PROFILE = {
  name: 'Pangeran Ryan Pahlevi',
  role: 'Full-Stack Web Architect & Next.js Specialist',
  tagline: 'Membangun Ekosistem Digital Berkinerja Tinggi, Skalabel, dan Berdaya Saing Global.',
  bio: 'Seorang Senior Full-Stack Engineer dengan keahlian mendalam pada arsitektur Next.js 14, React 18, TypeScript, Tailwind CSS, dan sistem backend enterprise (Laravel & Node.js). Berpengalaman mentransformasi sistem portal skala nasional (BRIN), ekosistem media & TV kampus (Universitas Budi Luhur), platform e-commerce UMKM, hingga sistem manajemen persewaan & smart city.',
  email: 'pangeranryan080504@gmail.com',
  whatsapp: '6281119333639',
  github: 'https://github.com/raphlv',
  location: 'Jakarta, Indonesia',
  availability: 'Tersedia untuk Proyek Klien / Konsultasi Sistem',
  stats: [
    { label: 'Repositori GitHub Nyata', value: '20+' },
    { label: 'Teknologi Utama Dikuasai', value: '15+' },
    { label: 'Tingkat Kepuasan Klien', value: '100%' },
    { label: 'Waktu Muat Rata-Rata', value: '<0.8s' },
  ],
};

export const ALL_PROJECTS: Project[] = [
  {
    id: 'brin-portal-next',
    name: 'BRIN Portal Next.js',
    repoName: 'brin-portal-next',
    title: 'Portal Modern Badan Riset dan Inovasi Nasional (BRIN)',
    category: 'Enterprise & Portals',
    tagline: 'Ekosistem Digital Riset Nasional dengan 12 OR, Layanan Terbuka ELSA, & Hibah RIIM',
    description: 'Modernisasi portal resmi BRIN RI menggunakan Next.js 14 App Router, TypeScript, dan Tailwind CSS dengan tema terang dominan putih-merah, integrasi 12 Organisasi Riset, 85 Pusat Riset, dan katalog 380+ instrumen lab ISO 17025.',
    problem: 'Sistem informasi riset sebelumnya terfragmentasi dari 30+ lembaga penelitian kementerian, membutuhkan portal terpadu berkecepatan tinggi dengan navigasi instan antar organisasi dan layanan sains.',
    solution: 'Membangun arsitektur modular Next.js 14 dengan Server-Side Rendering (SSR) & Static Site Generation (SSG), multi-category search, dan dashboard CMS admin kontrol terintegrasi.',
    techStack: ['Next.js 14', 'React 18', 'TypeScript', 'Tailwind CSS', 'Lucide Icons'],
    githubUrl: 'https://github.com/raphlv/brin-portal-next',
    liveDemoUrl: 'http://localhost:3008',
    featured: true,
    metrics: [
      { label: 'Organisasi Riset', value: '12 OR' },
      { label: 'Pusat Riset', value: '85 PR' },
      { label: 'Fasilitas Lab ELSA', value: '380+' },
      { label: 'Performa Lighthouse', value: '99/100' },
    ],
    highlights: [
      'Multi-filter Instant Search modal (Ctrl+K) untuk alat laboratorium, hibah RIIM, dan beasiswa.',
      'Direktori dinamis 12 Organisasi Riset lengkap dengan invensi dan fasilitas reaktor nuklir/megasains.',
      'CMS Admin Control Center terpadu untuk monitoring usulan riset & warta iptek.',
      'Desain simetris, rapi, dan responsive pada semua breakpoint layar desktop & mobile.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1507668077129-56e32842fceb?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'budiluhur-portal-next',
    name: 'Budi Luhur Portal Next.js',
    repoName: 'budiluhur-portal-next',
    title: 'Portal Web Resmi Universitas Budi Luhur',
    category: 'Enterprise & Portals',
    tagline: 'Portal Akademik & Komunitas Kampus Berbasis Next.js 14 & Prisma ORM',
    description: 'Portal perguruan tinggi generasi baru untuk Universitas Budi Luhur yang menyatukan informasi penerimaan mahasiswa baru (PMB), fakultas, riset kebudiluhuran, serta integrasi database Prisma & MySQL.',
    problem: 'Portal kampus sebelumnya membutuhkan penyegaran visual modern, kecepatan akses tinggi untuk puluhan ribu mahasiswa, dan integrasi data yang aman.',
    solution: 'Menerapkan Next.js 14 App Router, dynamic routing, Prisma ORM schema relasional, serta styling Tailwind yang mencerminkan identitas warna biru-kuning resmi Budi Luhur.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Prisma ORM', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/budiluhur-portal-next',
    liveDemoUrl: 'http://localhost:3001',
    featured: true,
    metrics: [
      { label: 'Fakultas & Prodi', value: '5 Fakultas' },
      { label: 'Arsitektur Data', value: 'Prisma ORM' },
      { label: 'Kecepatan Akses', value: '< 1 detik' },
    ],
    highlights: [
      'Sistem navigasi mega-menu akademik dan layanan terpadu mahasiswa.',
      'Model database relasional Prisma ORM yang terstruktur rapi.',
      'Optimasi SEO tingkat lanjut untuk ranking pencarian kampus di Google.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'budiluhur-tv-next',
    name: 'Budi Luhur TV Streaming Platform',
    repoName: 'budiluhur-tv-next',
    title: 'Platform Media Kreatif & Streaming Siaran Budi Luhur TV',
    category: 'Enterprise & Portals',
    tagline: 'Portal Siaran Televisi Kampus, Live Report & Produksi Video Kreatif',
    description: 'Platform streaming dan media visual modern untuk Budi Luhur TV, dilengkapi fitur live report lapangan, katalog program acara kreatif, profil tim produksi, dan panel manajemen jadwal siaran.',
    problem: 'Kebutuhan stasiun TV kampus untuk menyiarkan konten kreatif multi-program dan laporan langsung dengan interface modern setara stasiun TV profesional.',
    solution: 'Membangun portal siaran Next.js dengan video embed player berlatar dark visual cinematic, tab program mingguan, tim jurnalis, dan pelaporan langsung.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Lucide Icons', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/budiluhur-tv-next',
    liveDemoUrl: 'http://localhost:3000',
    featured: true,
    metrics: [
      { label: 'Program Unggulan', value: '10+ Acara' },
      { label: 'Kategori Liputan', value: 'Live & VOD' },
      { label: 'Format Video', value: 'Full HD' },
    ],
    highlights: [
      'Modul Live Report interaktif dengan update terkini dari lapangan.',
      'Struktur direktori tim kru kreatif dan jurnalis kampus.',
      'Desain sinematik modern dengan pemutar video responsif.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1578328819058-b69f3a3b0f6b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'radiobudiluhur-next',
    name: 'Radio Budi Luhur 107.7 FM',
    repoName: 'radiobudiluhur-next',
    title: 'Platform Web & Live Streaming Audio Radio Budi Luhur 107.7 FM',
    category: 'Enterprise & Portals',
    tagline: 'Stasiun Radio Streaming Mahasiswa, Podcast Hub, & Chart Top 20',
    description: 'Platform web interaktif untuk Radio Budi Luhur 107.7 FM yang menyajikan pemutar streaming audio real-time, tangga lagu Chart Top 20 mingguan, katalog podcast, dan perkenalan penyiar (announcer).',
    problem: 'Radio komunitas kampus membutuhkan kehadiran digital modern yang memungkinkan pendengar di luar jangkauan sinyal FM mendengarkan siaran langsung dari perangkat apapun.',
    solution: 'Mengembangkan audio player streaming non-stop dengan UI bertema electric blue & neon yellow resmi kampus, sistem tangga lagu voting, dan arsip podcast.',
    techStack: ['Next.js 14', 'TypeScript', 'Tailwind CSS', 'Web Audio API'],
    githubUrl: 'https://github.com/raphlv/radiobudiluhur-next',
    liveDemoUrl: 'http://localhost:3005',
    featured: true,
    metrics: [
      { label: 'Frekuensi FM', value: '107.7 FM' },
      { label: 'Chart Mingguan', value: 'Top 20 Lagu' },
      { label: 'Format Audio', value: 'High Bitrate Stream' },
    ],
    highlights: [
      'Continuous Audio Player yang tetap menyala saat pengguna berpindah halaman.',
      'Sistem Chart Top 20 interaktif dengan data lagu terupdate.',
      'Katalog podcast episode on-demand dan profil penyiar favorit.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1598488035139-bdbb2231ce04?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'rental',
    name: 'Sistem Persewaan Kendaraan & Aset (Rental)',
    repoName: 'rental',
    title: 'Enterprise Vehicle & Asset Rental Management System',
    category: 'Management & ERP',
    tagline: 'Sistem Informasi Manajemen Armada, Reservasi, & Pembayaran Rental',
    description: 'Aplikasi manajemen persewaan kendaraan dan inventaris aset berbasis web dengan kalkulasi tarif otomatis, status ketersediaan armada, pencatatan transaksi, dan laporan laba rugi.',
    problem: 'Pengelolaan rental armada yang masih manual rentan bentrok jadwal peminjaman, salah hitung denda keterlambatan, dan pelacakan unit yang sulit.',
    solution: 'Merancang sistem terpusat dengan kalender ketersediaan armada real-time, verifikasi identitas penyewa, dan invoice otomatis.',
    techStack: ['Laravel 11', 'PHP', 'Blade', 'Bootstrap/Tailwind', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/rental',
    featured: true,
    metrics: [
      { label: 'Modul Sistem', value: 'Armada & Keuangan' },
      { label: 'Otomasi Tarif', value: '100% Otomatis' },
      { label: 'Laporan', value: 'Export PDF/Excel' },
    ],
    highlights: [
      'Manajemen data armada kendaraan dengan riwayat servis & ketersediaan.',
      'Sistem booking dengan kalkulasi durasi sewa dan denda otomatis.',
      'Dashboard analitik pendapatan harian dan bulanan.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'kusuma-craft',
    name: 'Kusuma Craft E-Commerce',
    repoName: 'kusuma-craft',
    title: 'Platform E-Commerce Kerajinan Tangan & Souvenir Nusantara',
    category: 'E-Commerce & UMKM',
    tagline: 'Katalog Produk Seni Handcraft, Keranjang Belanja, & Checkout Terpadu',
    description: 'Website toko online untuk UMKM kerajinan tangan lokal Kusuma Craft dengan etalase produk bernuansa estetik, filter kategori bahan baku, keranjang belanja dinamis, dan integrasi pesanan via WhatsApp/Email.',
    problem: 'Pengrajin lokal membutuhkan sarana pemasaran digital untuk menjangkau pasar suvenir korporat dan pembeli retail dari seluruh Indonesia.',
    solution: 'Membangun web e-commerce bernuansa natural dan elegan, memudahkan pembeli memilih variasi produk kerajinan dan langsung memesan.',
    techStack: ['PHP', 'Laravel', 'Tailwind CSS', 'MySQL', 'JavaScript'],
    githubUrl: 'https://github.com/raphlv/kusuma-craft',
    featured: true,
    metrics: [
      { label: 'Kategori Produk', value: 'Handcraft & Seni' },
      { label: 'Proses Checkout', value: 'Instan WhatsApp' },
      { label: 'Tampilan Mobile', value: '100% Responsif' },
    ],
    highlights: [
      'Galeri visual produk beresolusi tinggi dengan rincian spesifikasi dimensi.',
      'Sistem keranjang belanja dan formulir pemesanan ringkas.',
      'Panel manajemen produk untuk mengunggah kerajinan baru dengan mudah.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1513519245088-0e12902e5a38?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'khumairasnack',
    name: 'Khumaira Snack E-Commerce',
    repoName: 'khumairasnack',
    title: 'Platform Penjualan Kuliner & Snack UMKM Khumaira',
    category: 'E-Commerce & UMKM',
    tagline: 'Katalog Camilan Higienis, Pemesanan Online, & Pengiriman Cepat',
    description: 'Sistem informasi penjualan dan pemesanan online camilan khas nusantara dengan kalkulasi berat ongkir, varian rasa, dan promosi musiman.',
    problem: 'Pemesanan camilan melalui media sosial sering kali tercecer dan memakan waktu konfirmasi pesanan secara manual.',
    solution: 'Menghadirkan portal katalog terstruktur di mana pelanggan dapat memilih paket snack favorit dan menerima ringkasan order otomatis.',
    techStack: ['PHP', 'Bootstrap', 'MySQL', 'jQuery'],
    githubUrl: 'https://github.com/raphlv/khumairasnack',
    featured: false,
    metrics: [
      { label: 'Katalog Snack', value: '25+ Menu' },
      { label: 'Waktu Order', value: '< 2 Menit' },
    ],
    highlights: [
      'Katalog camilan terbagi per kategori manis, gurih, dan hampers oleh-oleh.',
      'Struktur formulir order simpel yang langsung terhubung ke admin toko.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1599490659213-e2b9527bd087?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'golf-indonesia',
    name: 'Golf Indonesia Platform',
    repoName: 'golf-indonesia',
    title: 'Sistem Informasi & Reservasi Komunitas Golf Nasional',
    category: 'Management & ERP',
    tagline: 'Manajemen Tee Time, Lapangan Golf, & Keanggotaan Turnamen',
    description: 'Aplikasi web manajemen olahraga golf di Indonesia yang mencakup direktori lapangan golf profesional, jadwal tee time, pendaftaran turnamen, dan skor handicap.',
    problem: 'Pemain dan komunitas golf kesulitan menemukan informasi ketersediaan jadwal tee time dan mendaftar turnamen antar-klub secara terpadu.',
    solution: 'Membangun aplikasi manajemen lapangan dengan visual prestisius, jadwal booking lapangan, dan papan peringkat turnamen.',
    techStack: ['PHP', 'Laravel', 'Blade', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/golf-indonesia',
    featured: false,
    metrics: [
      { label: 'Direktori Lapangan', value: 'Nasional' },
      { label: 'Fitur', value: 'Tee Time & Skor' },
    ],
    highlights: [
      'Pemesanan jadwal tee-time lapangan golf dengan filter kota.',
      'Sistem registrasi turnamen dan rekapitulasi leaderboard.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1535131749006-b7f58c99034b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'bencana',
    name: 'Sistem Informasi Tanggap Bencana',
    repoName: 'bencana',
    title: 'Sistem Pemantauan, Pelaporan, & Mitigasi Bencana Real-Time',
    category: 'Smart City & Public',
    tagline: 'Platform Pelaporan Cepat Bencana Alam & Distribusi Bantuan Logistik',
    description: 'Sistem informasi kebencanaan yang memungkinkan warga dan relawan melaporkan kejadian banjir, longsor, atau gempa bumi secara real-time disertai titik lokasi dan kebutuhan logistik darurat.',
    problem: 'Keterlambatan koordinasi penyaluran bantuan saat bencana akibat data kebutuhan korban yang simpang siur.',
    solution: 'Menyediakan dashboard pelaporan terverifikasi dengan pemetaan status darurat dan posko bantuan.',
    techStack: ['PHP', 'Bootstrap', 'Leaflet JS', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/bencana',
    featured: true,
    metrics: [
      { label: 'Waktu Pelaporan', value: 'Real-Time' },
      { label: 'Pemetaan', value: 'Geospasial Koordinat' },
    ],
    highlights: [
      'Peta sebaran posko pengungsian dan tingkat keparahan bencana.',
      'Sistem pencatatan stok logistik bantuan makanan dan obat-obatan.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1547683905-f686c993aae5?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'jit-resolve',
    name: 'JIT Resolve IT Helpdesk',
    repoName: 'jit-resolve',
    title: 'Sistem Manajemen Tiket Kendala TI Just-In-Time',
    category: 'Management & ERP',
    tagline: 'Tracking Masalah IT, Service Level Agreement (SLA), & Resolusi Cepat',
    description: 'Platform manajemen tiket kendala TI korporat yang menerapkan prinsip Just-In-Time untuk memprioritaskan penyelesaian insiden sistem dan perangkat keras sesuai SLA.',
    problem: 'Keluhan kendala teknis karyawan sering tertunda karena tidak adanya sistem penugasan tiket dan monitoring waktu penyelesaian.',
    solution: 'Membangun aplikasi helpdesk dengan alur tiket berjenjang (Open, In-Progress, Resolved) dan laporan performa teknisi.',
    techStack: ['Laravel', 'PHP', 'Blade', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/jit-resolve',
    featured: false,
    metrics: [
      { label: 'Penanganan SLA', value: 'Otomatis' },
      { label: 'Status Tiket', value: 'Live Tracking' },
    ],
    highlights: [
      'Formulir submit insiden dengan lampiran tangkapan layar kendala.',
      'Dashboard beban kerja teknisi dan durasi rata-rata penyelesaian.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'igakerta',
    name: 'Sistem Layanan Publik Desa Iga Kerta',
    repoName: 'igakerta',
    title: 'Portal Pelayanan Publik & Transparansi Administrasi Desa',
    category: 'Smart City & Public',
    tagline: 'Digitalisasi Surat Menyurat Warga, Bansos, & Anggaran Desa',
    description: 'Aplikasi tata kelola pemerintahan desa yang melayani pengajuan surat keterangan domisili/usaha online, transparansi realisasi APBDes, dan data kependudukan.',
    problem: 'Warga desa harus datang langsung ke kantor desa pada jam kerja untuk mengurus surat pengantar sederhana.',
    solution: 'Mendigitalisasi formulir permohonan surat sehingga warga dapat mengajukan secara online dengan verifikasi barcode.',
    techStack: ['Laravel', 'Blade', 'MySQL', 'Bootstrap'],
    githubUrl: 'https://github.com/raphlv/igakerta',
    featured: false,
    metrics: [
      { label: 'Layanan Surat', value: 'Digital Barcode' },
      { label: 'Transparansi', value: 'APBDes Terbuka' },
    ],
    highlights: [
      'Modul permohonan surat administrasi warga dengan unduh PDF instan.',
      'Grafik infografis kependudukan dan transparansi dana desa.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1500382017468-9049fed747ef?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'atlas',
    name: 'Atlas GIS Pemetaan Spasial',
    repoName: 'atlas',
    title: 'Aplikasi Pemetaan Interaktif & Visualisasi Data Geospasial',
    category: 'Smart City & Public',
    tagline: 'Sistem Informasi Geografis (GIS) Berbasis Web & Layering Wilayah',
    description: 'Platform visualisasi data spasial wilayah dengan kemampuan filtering layer tematik, penandaan koordinat aset daerah, dan analisis demografi berbasis peta.',
    problem: 'Analisis data aset daerah sulit dipahami pembuat kebijakan jika hanya disajikan dalam bentuk tabel spreadsheet konvensional.',
    solution: 'Membuat web GIS interaktif yang menampilkan polygon batas wilayah, titik fasilitas, dan filtering data spasial.',
    techStack: ['PHP', 'JavaScript', 'Leaflet/Mapbox', 'GeoJSON', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/atlas',
    featured: false,
    metrics: [
      { label: 'Layering Data', value: 'Multi-Layer GIS' },
      { label: 'Format Peta', value: 'GeoJSON / Tile' },
    ],
    highlights: [
      'Visualisasi peta interaktif dengan zoom tingkat tinggi dan info popup.',
      'Filter layer berdasarkan kategori infrastruktur dan zonasi.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1524661135-423995f22d0b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'apl_BankSampah',
    name: 'Aplikasi Bank Sampah Digital',
    repoName: 'apl_BankSampah',
    title: 'Platform Manajemen Bank Sampah & Ekonomi Sirkular Warga',
    category: 'Smart City & Public',
    tagline: 'Konversi Sampah Menjadi Saldo Tabungan Digital yang Bernilai Ekonomis',
    description: 'Sistem pencatatan setoran sampah anorganik (plastik, kertas, logam) oleh nasabah warga dengan konversi saldo tabungan, harga timbangan otomatis, dan riwayat penarikan dana.',
    problem: 'Pencatatan buku tabungan sampah manual sering hilang, rentan salah hitung timbangan, dan kurang memotivasi warga.',
    solution: 'Menghadirkan aplikasi buku tabungan digital di mana nasabah dapat melihat pertumbuhan saldo rupiah dari hasil pilah sampah.',
    techStack: ['PHP', 'MySQL', 'JavaScript', 'HTML5/CSS3'],
    githubUrl: 'https://github.com/raphlv/apl_BankSampah',
    featured: false,
    metrics: [
      { label: 'Kategori Sampah', value: 'Plastik/Logam/Kertas' },
      { label: 'Dampak', value: 'Ekonomi Hijau' },
    ],
    highlights: [
      'Kalkulasi otomatis harga per kilogram sesuai jenis sampah terkini.',
      'Buku tabungan digital nasabah dengan riwayat transaksi lengkap.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'siswa',
    name: 'Sistem Informasi Manajemen Siswa',
    repoName: 'siswa',
    title: 'Aplikasi Administrasi Data Siswa, Nilai, & Presensi Akademik',
    category: 'Management & ERP',
    tagline: 'Manajemen Buku Induk Siswa, Rapor Digital, & Rekapitulasi Kehadiran',
    description: 'Sistem administrasi terpadu untuk sekolah dalam mengelola data induk kependidikan, input nilai harian/ujian, rekap presensi kelas, dan pencetakan rapor digital.',
    problem: 'Guru dan tata usaha menghabiskan waktu berhari-hari untuk merekap nilai dan mencetak rapor fisik siswa.',
    solution: 'Otomatisasi pengolahan nilai mata pelajaran dengan batas KKM dan generate rapor siswa secara terpusat.',
    techStack: ['PHP', 'MySQL', 'Bootstrap', 'JavaScript'],
    githubUrl: 'https://github.com/raphlv/siswa',
    featured: false,
    metrics: [
      { label: 'Manajemen Data', value: 'Siswa, Guru, Nilai' },
      { label: 'Output', value: 'Rapor Digital PDF' },
    ],
    highlights: [
      'Input nilai bertingkat oleh guru mata pelajaran dengan kalkulasi rata-rata otomatis.',
      'Modul presensi siswa dengan rekap persentase kehadiran per semester.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'jurnal',
    name: 'Platform Jurnal Ilmiah Akademik',
    repoName: 'jurnal',
    title: 'Sistem Manajemen Pengajuan & Peer-Review Artikel Jurnal',
    category: 'Enterprise & Portals',
    tagline: 'Workflow Publikasi Karya Ilmiah, Editorial Board, & Pengindeksan',
    description: 'Platform manajemen publikasi jurnal ilmiah berkala yang memfasilitasi alur submission manuskrip, proses blind peer-review oleh reviewer, revisi penulis, dan penerbitan volume ber-DOI.',
    problem: 'Pengelolaan artikel jurnal melalui korespondensi email tidak terstruktur dan menyulitkan pelacakan status naskah.',
    solution: 'Membangun workflow sistematis dari naskah masuk, penugasan reviewer, hingga final approval naskah terbit.',
    techStack: ['PHP', 'MySQL', 'Tailwind CSS', 'JavaScript'],
    githubUrl: 'https://github.com/raphlv/jurnal',
    featured: false,
    metrics: [
      { label: 'Alur Penerbitan', value: 'Double Blind Review' },
      { label: 'Akses', value: 'Open Access Journal' },
    ],
    highlights: [
      'Sistem tracking status naskah bagi author secara transparan.',
      'Panel penilaian khusus untuk reviewer dengan form kriteria evaluasi.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1456513080510-7bf3a84b82f8?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'zanilove',
    name: 'Zanilove Fashion & Beauty',
    repoName: 'zanilove',
    title: 'E-Commerce Katalog Busana & Produk Kecantikan Zanilove',
    category: 'E-Commerce & UMKM',
    tagline: 'Etalase Fashion Modern, Panduan Ukuran, & Belanja Mudah',
    description: 'Website katalog toko fashion wanita dan produk perawatan kecantikan dengan antarmuka bersih, filter ukuran busana, dan checkout interaktif.',
    problem: 'Pelanggan membutuhkan katalog visual yang memuat rincian bahan baju dan panduan ukuran jelas sebelum membeli.',
    solution: 'Merancang toko online bertema modern chic dengan panduan ukuran terintegrasi dan sistem order cepat.',
    techStack: ['PHP', 'HTML5/CSS3', 'JavaScript', 'MySQL'],
    githubUrl: 'https://github.com/raphlv/zanilove',
    featured: false,
    metrics: [
      { label: 'Kategori', value: 'Fashion & Skincare' },
      { label: 'Interface', value: 'Modern Chic' },
    ],
    highlights: [
      'Filter produk berdasarkan kategori pakaian, warna, dan rentang harga.',
      'Integrasi tombol tanya produk langsung ke admin customer service.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'apl_Catering',
    name: 'Aplikasi Catering Sehat Online',
    repoName: 'apl_Catering',
    title: 'Sistem Pemesanan Paket Catering Harian & Acara Khusus',
    category: 'E-Commerce & UMKM',
    tagline: 'Langganan Meal Plan Sehat, Fleksibel, & Mendukung UMKM Kuliner',
    description: 'Aplikasi pemesanan catering berbasis web yang memungkinkan pelanggan mengatur jadwal pengiriman menu harian, kustomisasi diet sehat, dan reservasi paket prasmanan acara besar.',
    problem: 'Konsumen repot menyiapkan makanan sehat setiap hari dan penyedia catering sulit mendata jadwal menu langganan pelanggan.',
    solution: 'Menyediakan kalender pemesanan meal plan di mana pengguna dapat memilih variasi menu per hari dalam satu minggu.',
    techStack: ['PHP', 'HTML5/CSS3', 'MySQL', 'JavaScript'],
    githubUrl: 'https://github.com/raphlv/apl_Catering',
    featured: false,
    metrics: [
      { label: 'Paket Menu', value: 'Harian & Event' },
      { label: 'Opsi Diet', value: 'Custom Kalori' },
    ],
    highlights: [
      'Kalender meal plan mingguan dengan pilihan menu berbeda setiap hari.',
      'Sistem pemilihan porsi dan alamat pengantaran fleksibel.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1555244162-803834f70033?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'jule-publicspeaking',
    name: 'Jule Public Speaking & Communication',
    repoName: 'jule-publicspeaking',
    title: 'Landing Page & Platform Edukasi Komunikasi Jule Academy',
    category: 'Enterprise & Portals',
    tagline: 'Pelatihan Percaya Diri, Public Speaking Profesional, & Master of Ceremony',
    description: 'Landing page promosi dan pendaftaran workshop pelatihan keterampilan komunikasi publik, vocal coaching, dan presentasi bisnis berkonversi tinggi.',
    problem: 'Penyedia kursus membutuhkan landing page kredibel dengan testimoni alumni dan alur pendaftaran batch kelas yang jelas.',
    solution: 'Membangun landing page berdaya pikat tinggi dengan video trailer materi, jadwal kelas, dan form pendaftaran langsung.',
    techStack: ['PHP', 'Tailwind CSS', 'JavaScript', 'HTML5'],
    githubUrl: 'https://github.com/raphlv/jule-publicspeaking',
    featured: false,
    metrics: [
      { label: 'Modul Kelas', value: 'Beginner & Pro' },
      { label: 'Konversi Pendaftaran', value: 'Tinggi' },
    ],
    highlights: [
      'Silabus materi pelatihan komunikasi dengan rincian durasi per sesi.',
      'Formulir pendaftaran peserta dengan konfirmasi otomatis.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1475721027785-f74eccf877e2?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'stream-overlay',
    name: 'Stream Overlay Studio Suite',
    repoName: 'stream-overlay',
    title: 'Custom Live Streaming Overlay, Widget, & Animasi Siaran',
    category: 'Smart City & Public',
    tagline: 'Widget Interaktif OBS/Streamlabs untuk Streamer & Media Broadcast',
    description: 'Kumpulan overlay siaran langsung interaktif berbasis web (HTML5/CSS3/JavaScript) untuk keperluan live stream Twitch/YouTube/OBS studio dengan notifikasi animasi real-time.',
    problem: 'Streamer dan stasiun TV sering kali membutuhkan tampilan grafik on-screen dinamis yang ringan dan tidak membebani performa komputer siaran.',
    solution: 'Mengembangkan browser source overlay berbasis web yang ringan, mulus 60 FPS, dan mudah dikonfigurasi via parameter URL.',
    techStack: ['JavaScript', 'HTML5 Canvas', 'CSS Animations', 'OBS Browser Source'],
    githubUrl: 'https://github.com/raphlv/stream-overlay',
    featured: false,
    metrics: [
      { label: 'Frame Rate', value: '60 FPS Smooth' },
      { label: 'Kompatibilitas', value: 'OBS / vMix' },
    ],
    highlights: [
      'Animasi lower-third dan frame kamera yang responsif.',
      'Widget hitung mundur waktu siaran dan peringatan interaktif.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?q=80&w=1000&auto=format&fit=crop',
  },
  {
    id: 'budiluhur-tv',
    name: 'Budi Luhur TV Core Laravel Engine',
    repoName: 'budiluhur-tv',
    title: 'Portal Siaran Televisi Kampus Berbasis Laravel 11 & Blade',
    category: 'Enterprise & Portals',
    tagline: 'Backend Engine & CMS Portal Penyiaran Konten Kampus',
    description: 'Implementasi arsitektur MVC Laravel untuk Budi Luhur TV yang mengelola autentikasi redaksi, upload thumbnail video, integrasi basis data penonton, dan sistem berita terhubung.',
    problem: 'Sistem manajemen konten penyiaran memerlukan panel redaksi yang aman dengan hak akses berjenjang untuk produser, editor, dan reporter.',
    solution: 'Merancang sistem otentikasi role-based access control (RBAC) di Laravel dengan validasi unggahan media dan caching query database.',
    techStack: ['Laravel 11', 'PHP', 'Blade', 'MySQL', 'Bootstrap'],
    githubUrl: 'https://github.com/raphlv/budiluhur-tv',
    featured: false,
    metrics: [
      { label: 'Framework', value: 'Laravel 11' },
      { label: 'Keamanan', value: 'RBAC & CSRF Shield' },
    ],
    highlights: [
      'Dashboard manajemen jadwal tayang dan liputan liputan khusus.',
      'Sistem komentar dan interaksi pemirsa dengan moderasi otomatis.',
    ],
    imageUrl: 'https://images.unsplash.com/photo-1492691527719-9d1e07e534b4?q=80&w=1000&auto=format&fit=crop',
  },
];

export const SKILL_CATEGORIES = [
  {
    title: 'Frontend Engineering',
    skills: [
      { name: 'Next.js 14 (App Router)', level: 'Expert', icon: '⚡' },
      { name: 'React 18 & Hooks', level: 'Expert', icon: '⚛️' },
      { name: 'TypeScript', level: 'Advanced', icon: '📘' },
      { name: 'Tailwind CSS & Styling', level: 'Expert', icon: '🎨' },
      { name: 'Redux Toolkit / Zustand', level: 'Advanced', icon: '🔄' },
      { name: 'Responsive UI & UX Animation', level: 'Expert', icon: '✨' },
    ],
  },
  {
    title: 'Backend & Database Architecture',
    skills: [
      { name: 'Node.js & Express', level: 'Advanced', icon: '🟢' },
      { name: 'Laravel 11 & PHP 8.x', level: 'Expert', icon: '🔴' },
      { name: 'Prisma ORM & Eloquent', level: 'Expert', icon: '💎' },
      { name: 'MySQL & PostgreSQL', level: 'Expert', icon: '🗄️' },
      { name: 'RESTful API & GraphQL', level: 'Expert', icon: '🔌' },
      { name: 'Redis Caching & Auth (JWT/OAuth)', level: 'Advanced', icon: '🛡️' },
    ],
  },
  {
    title: 'DevOps, Tools & Performance',
    skills: [
      { name: 'Git & GitHub Workflow', level: 'Expert', icon: '🐙' },
      { name: 'Vercel / Cloud Deployment', level: 'Expert', icon: '☁️' },
      { name: 'Docker & Containerization', level: 'Intermediate', icon: '🐳' },
      { name: 'SEO & Core Web Vitals (>95)', level: 'Expert', icon: '🚀' },
      { name: 'Laragon / Nginx / Apache', level: 'Advanced', icon: '⚙️' },
    ],
  },
];

export const CLIENT_TESTIMONIALS = [
  {
    name: 'Dr. Hendra Gunawan, M.Kom.',
    role: 'Ketua Tim Transformasi Digital',
    org: 'Sektor Pendidikan & Riset Tinggi',
    content: 'Pangeran Ryan berhasil mentransformasi portal web dan arsitektur sistem kami menjadi jauh lebih cepat, modern, dan sangat intuitif. Penguasaan Next.js dan TypeScript-nya di atas rata-rata industri!',
    rating: 5,
  },
  {
    name: 'Siti Nurhaliza, S.Ds.',
    role: 'Founder & Creative Lead',
    org: 'Kusuma Craft Nusantara',
    content: 'Website toko online yang dibuatkan sangat memukau klien korporat kami. Tampilan estetik, pemesanan WhatsApp lancar, dan penjualan produk meningkat lebih dari 200% dalam 3 bulan pertama.',
    rating: 5,
  },
  {
    name: 'Bambang Supriyanto',
    role: 'Direktur Operasional',
    org: 'Armada Rental & Logistik',
    content: 'Sistem manajemen persewaan yang dibangun menghilangkan masalah bentrok jadwal dan salah hitung tarif. Kodenya rapi, proses pengerjaan tepat waktu, dan komunikasinya sangat profesional.',
    rating: 5,
  },
];

export const ESTIMATOR_PACKAGES = [
  {
    id: 'landing',
    name: 'Landing Page & Company Profile',
    desc: 'Website representasi profesional berkinerja tinggi, estetik, dan SEO-optimized untuk perusahaan, instansi, atau brand personal.',
    estimatedDuration: '1 - 2 Minggu',
    features: ['Custom Next.js / Tailwind Design', 'Mobile-First Responsive', 'SEO On-Page & Schema Markup', 'WhatsApp & Email Inquiry', 'Domain & Hosting Setup'],
  },
  {
    id: 'ecommerce',
    name: 'E-Commerce & Toko Online UMKM',
    desc: 'Platform penjualan produk digital/fisik lengkap dengan etalase katalog, keranjang belanja, checkout instan, dan CMS admin.',
    estimatedDuration: '2 - 3 Minggu',
    features: ['Katalog Produk & Variasi', 'Keranjang Belanja & Checkout WA/Payment', 'Dashboard Admin Kelola Stok', 'Kalkulasi Ongkir Otomatis', 'Optimasi Kecepatan Gambar'],
  },
  {
    id: 'portal',
    name: 'Portal Institusi & Media Streaming',
    desc: 'Ekosistem web multi-halaman untuk institusi pendidikan, media berita, atau siaran streaming dengan arsitektur data dinamis.',
    estimatedDuration: '3 - 5 Minggu',
    features: ['Arsitektur Next.js 14 App Router', 'Multi-Category Search (Ctrl+K)', 'Streaming Audio / Video Embed Player', 'CMS Redaksi & Multi-Role Admin', 'Database Relasional Teroptimasi'],
  },
  {
    id: 'custom-saas',
    name: 'Custom SaaS & Sistem Manajemen (ERP)',
    desc: 'Sistem informasi kustom kompleks untuk operasional bisnis (Rental, Helpdesk SLA, Smart City, Inventaris Aset).',
    estimatedDuration: '4 - 8 Minggu',
    features: ['Role-Based Access Control (RBAC)', 'Otomasi Logika Bisnis & Kalkulasi', 'Laporan Analitik & Export PDF/Excel', 'Integrasi API & Layanan Eksternal', 'Garansi Pemeliharaan & Support'],
  },
];
